FROM golang:1.24-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -trimpath -ldflags='-s -w' -o /capital-allocator ./cmd/capital-allocator

FROM gcr.io/distroless/static-debian12:nonroot
COPY --from=builder /capital-allocator /capital-allocator
COPY configs/ /configs/
ENTRYPOINT ["/capital-allocator"]
